Feat[EGB-011]create students,  grades and record books controllers
Rails-of-legion/electronic_grade_book pull request #32
Opened 2024-04-17 11:35 UTC by stanislav-plisko

2024-04-17 14:40 UTC, Sergick12 requested changes

2024-04-17 14:40 UTC, Sergick12 commented on Procfile.dev
> +css: yarn watch:css
better this remove

2024-04-17 14:40 UTC, Sergick12 commented on app/controllers/grades_controller.rb
> +  end
add empty line

2024-04-17 14:40 UTC, Sergick12 commented on app/controllers/record_books_controller.rb
> +  end
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/controllers/students_controller.rb
> +  end
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/views/grades/edit.html.erb
> +<%= link_to 'Назад', grades_path, class: 'btn btn-secondary mt-3' %>
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/views/grades/index.html.erb
> +<%= link_to 'Создать новую оценку', new_grade_path, class: 'btn btn-primary' %>
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/views/grades/new.html.erb
> +<%= link_to 'Назад', grades_path, class: 'btn btn-secondary mt-3' %>
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/views/grades/show.html.erb
> +<%= link_to 'Назад', grades_path, class: 'btn btn-secondary' %>
It too

2024-04-17 14:40 UTC, Sergick12 commented on app/views/record_books/_form.html.erb
> +  <% end %>
All files

2024-04-17 14:40 UTC, Sergick12 commented on app/views/record_books/new.html.erb
> +<%= link_to 'Назад', record_books_path, class: 'btn btn-light' %>
Dont use Russian

2024-04-17 14:40 UTC, Sergick12 commented on app/views/students/index.html.erb
> +        <th>ФИО</th>
Dont use rusian in all files

2024-04-17 14:40 UTC, Sergick12 commented on spec/controllers/students_controller_spec.rb
> +#require 'rails_helper'
remove folder spec/controllers

2024-04-18 14:00 UTC, Baron-Dmitry requested changes

2024-04-18 14:00 UTC, Baron-Dmitry commented on app/views/grades/_form.html.erb
> +
add empty line

2024-04-18 14:00 UTC, Baron-Dmitry commented on app/models/grade.rb
> +  has_one :subject, through: :record_book
Why does this association exist

2024-04-18 14:00 UTC, Baron-Dmitry commented on app/models/grade.rb
look at the database diagram, what rows and what connections should be

2024-04-19 07:46 UTC, Baron-Dmitry approved these changes, later dismissed

2024-04-19 19:55 UTC, merged