EBG-22 create specialities table
Rails-of-legion/electronic_grade_book pull request #9
Opened 2024-04-12 18:51 UTC by stanislav-plisko

2024-04-12 20:38 UTC, Sergick12 commented
change nama PR, dont use russian
template: Feat [EGB-002] add gems, devise, rolify, cancancan

2024-04-12 20:44 UTC, Sergick12 requested changes

2024-04-12 20:44 UTC, Sergick12 commented on .rubocop.yml
> +Rails/UniqueValidationWithoutIndex:
why did you change this in this branch? 
rollback  this!

2024-04-12 20:44 UTC, Sergick12 commented on Gemfile
> -  gem 'lefthook'
it too

2024-04-12 20:44 UTC, Sergick12 commented on Gemfile.lock
> -    lefthook (1.6.10)
it too

2024-04-12 20:44 UTC, Sergick12 commented on Gemfile.lock
> -  lefthook
it too

2024-04-12 20:44 UTC, Sergick12 commented on spec/models/speciality_spec.rb
> +RSpec.describe Speciality do
where are tests?

2024-04-12 20:44 UTC, Sergick12 commented on spec/models/student_spec.rb
> +RSpec.describe Student do
it too

2024-04-14 11:59 UTC, closed without merging

2024-04-14 11:59 UTC, stanislav-plisko commented
not valid